# Generated by Django 3.1.7 on 2021-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='num1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='num2',
            field=models.CharField(max_length=100),
        ),
    ]
